
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Manage Courses',
    description: 'Generated by Arif Mehniyar',
}
export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`flex w-full ${inter.className}`}>
            {children}
        </body></html>
    )
}