import '../styles/globals.css'
import {Sidebar} from '@/components/sidebar'
import { Inter } from 'next/font/google'
import {Navbar} from "@/components/navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Manage Courses',
  description: 'Generated by Arif Mehniyar',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex w-full ${inter.className}`}>
      <Sidebar></Sidebar>
      <div className="flex flex-col w-full bg-[#fcfcfc] min-h-screen">
          <Navbar></Navbar>
          {children}
      </div>
      </body>
    </html>
  )
}
